CREATE TABLE USERS (
    ID UUID NOT NULL,
    FIRST_NAME VARCHAR(45) NOT NULL,
    LAST_NAME VARCHAR(45) NOT NULL,
    USERNAME VARCHAR(55) NOT NULL UNIQUE,
    EMAIL VARCHAR(55) NOT NULL UNIQUE,
    PASSHASH VARCHAR(256) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE INDEX IDX_USERNAME ON USERS(USERNAME);

COMMENT ON TABLE USERS IS 'таблица для всех пользователей приложения';
COMMENT ON COLUMN USERS.PASSHASH IS 'колонка, где хранится hash пароля';