CREATE TABLE INVESTMENTS (
    ID UUID NOT NULL,
    TYPE_OF_INVESTMENTS TEXT NOT NULL,
    TIME_OF_INVESTMENT DATE NOT NULL DEFAULT CURRENT_DATE,
    AMOUNT NUMERIC NOT NULL,
    USER_ID UUID NOT NULL,
    CONSTRAINT FK_USER
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (ID)
);

COMMENT ON TABLE INVESTMENTS IS 'таблица для инвестиций пользователя';