CREATE TABLE USER_GROUP (
    USER_ID UUID NOT NULL,
    GROUP_ID UUID NOT NULL,

    CONSTRAINT FK_USER_ID
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (ID) ON UPDATE CASCADE,
    CONSTRAINT FK_GROUP_ID
        FOREIGN KEY (GROUP_ID)
            REFERENCES GROUPS (ID) ON UPDATE CASCADE ON DELETE CASCADE
);

COMMENT ON TABLE USER_GROUP IS 'таблица, которая связывает USERS и GROUPS';